#
# LXC
#

com.liferay.lxc.dxp.domains=www-dev.liferay.com
com.liferay.lxc.dxp.mainDomain=www-dev.liferay.com
com.liferay.lxc.dxp.server.protocol=https

#
# OAuth
#

a7855d10-6a20-1f0e-7e21-53d8654a09d2.oauth2.headless.server.client.secret=XXXXX
9fc0c45b-d42f-1fcd-09c3-a4b8e6ec4268.oauth2.headless.server.client.secret=XXXXX

liferay.oauth.application.external.reference.codes=\
    XXXXX,\
    XXXXX