com.liferay.lxc.dxp.domains=www-dev.liferay.com
com.liferay.lxc.dxp.mainDomain=www-dev.liferay.com
com.liferay.lxc.dxp.server.protocol=https

#
# OAuth
#
# DEV
external-reference-code-dev.oauth2.headless.server.client.secret=secret-credential
external-reference-code-dev.oauth2.headless.server.client.id=id-credential

# PROD
external-reference-code-prod.oauth2.headless.server.client.secret=secret-credential
external-reference-code-prod.oauth2.headless.server.client.id=id-credential

#UAT
external-reference-code-uat.oauth2.headless.server.client.secret=secret-credential
external-reference-code-uat.oauth2.headless.server.client.id=id-credential

liferay.oauth.application.external.reference.codes=\
    external-reference-code-dev,\
    external-reference-code-prod,\
    external-reference-code-uat