feature.flag.LPD-34594=true
feature.flag.LPD-62272=true
feature.flag.LPD-94989=true
feature.flag.LPS-187142=true
feature.flag.ui.visible[dev]=true
jdbc.default.driverClassName=org.postgresql.Driver
jdbc.default.password=liferay
jdbc.default.url=jdbc:postgresql://database:5432/lportal
jdbc.default.username=liferay
minifier.enabled=false
minifier.inline.content.cache.size=0
passwords.default.policy.change.required=false
passwords.default.policy.changeable=true
setup.wizard.enabled=false
terms.of.use.required=false
theme.css.fast.load=false
theme.images.fast.load=false
upgrade.database.auto.run=true