dependencies {
	compileInclude group: "com.google.api.grpc", name: "proto-google-cloud-aiplatform-v1beta1", version: "0.81.0"
	compileInclude group: "com.google.api.grpc", name: "proto-google-cloud-vertexai-v1", version: "1.27.0"
	compileInclude group: "com.google.cloud", name: "google-cloud-aiplatform", version: "3.69.0"
	compileInclude group: "com.google.cloud", name: "google-cloud-vertexai", version: "1.27.0"
	compileOnly group: "com.google.protobuf", name: "protobuf-java", version: "3.25.5"
	compileOnly group: "com.liferay", name: "jakarta.ws.rs", version: "3.1.0.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "jakarta.persistence", name: "jakarta.persistence-api", version: "3.1.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly project(":apps:account:account-api")
	compileOnly project(":apps:object:object-api")
	compileOnly project(":apps:object:object-rest-api")
	compileOnly project(":apps:portal-configuration:portal-configuration-module-configuration-api")
	compileOnly project(":apps:portal-lock:portal-lock-api")
	compileOnly project(":apps:portal-odata:portal-odata-api")
	compileOnly project(":apps:portal-vulcan:portal-vulcan-api")
	compileOnly project(":core:petra:petra-concurrent")
	compileOnly project(":core:petra:petra-function")
	compileOnly project(":core:petra:petra-string")
	compileOnly project(":dxp:apps:ai-hub-pricing:ai-hub-pricing-rest-api")
	compileOnly project(":dxp:apps:ai-hub:ai-hub-api")
}