##
## Database
##

jdbc.default.driverClassName=org.postgresql.Driver
jdbc.default.url=jdbc:postgresql://database:5432/lportal
jdbc.default.username=liferay
jdbc.default.password=liferay

##
## Developer conveniences
##

setup.wizard.enabled=false

##
## Feature Flags
##

feature.flag.LPD-62272=true
